version: '3'

services:
    app:
        build: .
        container_name: app
        volumes:
            - .:/var/www
        networks:
            - app-network
    nginx:
        build: .docker/nginx
        container_name: nginx
        entrypoint: dockerize -template /etc/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf nginx
        command: -g "daemon off;" -c /etc/nginx/nginx.conf
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        environment:
            - NGINX_PORT=9000
            - NGINX_HOST=app
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_HOST=db
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-network
    redis:
        image: redis:alpine
        expose: 
            - 6379
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
    